### ISSUE TITLE
nice project

### ISSUE THREAD

**Issue by swoopyfpv** [SK-Hardwired/xavc_rtmd2srt#2]
hey, 

nice project! haven't tested it yet.
got a additional question (if this is the wrong place just delete my thread)

i was thinking about mounting my rx0II to my a6300, extract the gyro data, inject it into the a6300 file and try to stabilize it with sony catalist. didn't find any option to inject the gyro data.
do you think this could be possible?

**Comment by zxwanghongyi** [comment]
same question

**Comment by SK-Hardwired** [comment]
Hi!

I found the way to read and decode some accel/gyro data. But there are more stabilization related data written (like sensor movement, lens OSS movement, lens distortion params, e.t.c.). Also you couldn't just get data from one camera footage and put to another - it won't work. Because there is space between two cameras and one's data will not fit to another physically - there should be some sort of parallax. ;)
